# Configuración básica del sitio
title: "Mi primer tema de programación"
description: "Un sitio web simple usando Jekyll y Markdown"
baseurl: "" # La URL base de tu sitio, por ejemplo, /blog
url: "https://davidgonzalezmare.github.io/PruebasTema1/" # La URL completa de tu sitio

# Configuración del autor
author:
  name: "David González"
  email: "d.gonzalezarco@edu.gva.es"

# Tema de Jekyll
theme: minima

# Procesador de Markdown
markdown: kramdown

# Plugins de Jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuración de la navegación
paginate: 5
paginate_path: "/page:num/"

# Excluir archivos y carpetas
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
